name: NYTPhotoViewer

options:
  bundleIdPrefix: io.ucb.anderson
  tabWidth: 2
  usesTabs: false
  indentWidth: 2
  developmentLanguage: "en"
  deploymentTarget:
    iOS: 12.0

settings:
  DEVELOPMENT_TEAM: PN8K78V28P
  GENERATE_INFOPLIST_FILE: YES
  CURRENT_PROJECT_VERSION: 5.0.8
  MARKETING_VERSION: 1

targets:
  NYTPhotoViewer:
    platform: iOS
    type: framework.static
    sources:
      - path: NYTPhotoViewer/NYTPhotoViewer
        createIntermediateGroups: true
        excludes: 
          - "**/NYTPhotoViewerCore.h"
          - "**/NYTInterstitialViewController.h"
        headerVisibility: public
      - path: NYTPhotoViewer/NYTPhotoViewer
        includes:
          - "**/NYTPhotoViewerCore.h"
          - "**/NYTInterstitialViewController.h"
        headerVisibility: project
    settings:
      base:
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        SKIP_INSTALL: YES
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: 1
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
  NYTPhotoViewerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: NYTPhotoViewer/UnitTests
        createIntermediateGroups: true

    dependencies:
      - target: NYTPhotoViewer

    settings:
      base:
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: 1
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
  Host:
    type: application
    platform: iOS
    sources:
      - path: NYTPhotoViewer/Examples/Sources/Swift/
      - path: NYTPhotoViewer/Examples/Resources
        excludes: 
          - "**/Info.plist"

    dependencies:
      - framework: $(BUILT_PRODUCTS_DIR)/NYTPhotoViewer.framework
    settings:
      base:
        INFOPLIST_FILE: NYTPhotoViewer/Examples/Sources/Swift/Example-Swift.plist
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: 1
        OTHER_LDFLAGS:
          - "-ObjC"
