name: PhotoBrowser

options:
  bundleIdPrefix: io.ucb.anderson
  tabWidth: 2
  usesTabs: false
  indentWidth: 2
  developmentLanguage: "en"
  deploymentTarget:
    iOS: 12.0
    macOS: 13.0

settings:
  DEVELOPMENT_TEAM: PN8K78V28P
  GENERATE_INFOPLIST_FILE: YES
  CURRENT_PROJECT_VERSION: 3.1.5
  MARKETING_VERSION: 1

targets:
  PhotoBrowser:
    platform: iOS
    type: framework
    sources:
      - path: PhotoBrowser/Sources/ 
        createIntermediateGroups: true
    settings:
      base:
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        SKIP_INSTALL: YES
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: 1

  # PhotoBrowserTests:
  #   type: bundle.unit-test
  #   platform: macOS
  #   sources:
  #     - path: Tests/
  #       createIntermediateGroups: true

  #   dependencies:
  #     - target: PhotoBrowser

  #   settings:
  #     base:
  #       SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
  #       TARGETED_DEVICE_FAMILY: "1,6,7"

  Host:
    type: application
    platform: iOS
    sources:
      - path: Host/
    dependencies:
      - framework: $(BUILT_PRODUCTS_DIR)/PhotoBrowser.framework
    settings:
      base:
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: 1

